package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.AktivElem.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.ArrayList;

public abstract class AktivElem extends Mezo {
	private int maxCso;

	public abstract void Frissit() throws Exception;

	/**
	 * A Játékosok ezen a függvényen keresztül csatolhatnak fel elemeket.
	 * @Override
	 */
	@Override
	public Boolean SzomszedFelcsatol(Mezo m) {
		// Ha nincs hely, akkor visszautasítunk
		if (GetSzomszedok().size() >= maxCso) {
			return false;
		}

		SzomszedHozzaad(m);
		return true;

	}

	/**
	 * A játékosok által lecsatlakoztatható szomszédokkal tér vissza.
	 * @Override
	 */
	@Override
	public ArrayList<Mezo> GetLeszedhetoSzomszedok() {
		return GetSzomszedok();
	}
}
