package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.AktivElem.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public abstract class AktivElem extends Mezo {
	private int maxCso;

	/**
	 * Az aktív elem konstruktora.
	 * Beállítja a maxJatekosok értékét Integer.MAX_VALUE-re. (Ez azt jelenti, hogy nincs korlát a játékosok számára.)
	 */
	public AktivElem()
	{
		super(Integer.MAX_VALUE);
	}

	public abstract void Frissit();
}
