package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Ciszterna.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class Ciszterna extends AktivElem {
	private Pumpa termeltpumpak;

	public void PumpaEltavolit() {
	}

	public void PumpatKeszit() {
	}

	public void CsovetKeszit() {
	}

	public void Frissit() {

	}
}
