package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Ciszterna.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferUnderflowException;
import java.util.List;

public class Ciszterna extends AktivElem {
	private Pumpa termeltpumpak;

	public void PumpaEltavolit() {
	}

	public void PumpatKeszit() {
	}

	public void CsovetKeszit() {
	}

	public void Frissit() {
		List<Cso> szomszedok = GetLeszedhetoSzomszedok();
		for (var cso:szomszedok) {
			try {
				cso.VizetCsokkent(1); //MAXVIZ
			}
			catch (BufferUnderflowException e){System.out.println("Csoben nincs eleg viz: " + 1 + " " + e);}
		}
	}
}
