package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Ciszterna.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferUnderflowException;
import java.util.List;
import java.util.ArrayList;

public class Ciszterna extends AktivElem {
	private  static int MAXVIZ = 1;
	private List<Pumpa> termeltpumpak;
	
	public Ciszterna() {
		termeltpumpak = new ArrayList<Pumpa>();
	}

	public void PumpaEltavolit() {
	}

	public void PumpatKeszit() {
	}

	public void CsovetKeszit() {
	}

	public void Frissit() {
		System.out.println("Függvényhívás: " + this +": Frissit() ");
		List<Mezo> szomszedok = GetLeszedhetoSzomszedok();
		for (var cso : szomszedok) {
			try {
				cso.VizetCsokkent(MAXVIZ);
			}
			catch (Exception e){/* Hmm ez nem szép itt ;) */}
		}
	}
	
	/**
	 * Egy mező szomszédaihoz hozzáad egy új mezőt
	 * @param m a hozzáadandó mező
	 */
	@Override
	public void SzomszedHozzaad(Mezo m) {
		ArrayList<Mezo> szomszedok = super.GetSzomszedok();
		szomszedok.add(m);
		System.out.println("Függvényhívás: " + this + ".SzomszedHozzaad("+m+")");
	}
}
