package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Cso.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.util.concurrent.ExecutionException;

public class Cso extends Mezo {
	private int vizmennyiseg;

	public void Megjavit() {
		setMukodik(true);
	}

	public void PumpaEpit() {
	}

	public void Kilyukaszt() {
		setMukodik(false);
	}

	public void VizetNovel(int meret) throws Exception {
		System.out.println("Függvényhívás:" + this +": VizetNovel( " + meret + ") ");
		if(meret + vizmennyiseg > 1){	//MAXVIZ
			int tulfolyas = meret+vizmennyiseg-1;
			vizmennyiseg += meret - tulfolyas;
			throw new Exception(String.valueOf(tulfolyas));
		}
		else {
			vizmennyiseg += meret;
		}
	}

	public void VizetCsokkent(int meret) throws Exception {
		System.out.println("Függvényhívás: " + this +": VizetCsokkent( " + meret + ") ");

		if(meret < vizmennyiseg) {
			vizmennyiseg -= meret;
		}
		else{
			int ki = vizmennyiseg;
			vizmennyiseg = 0;
			throw new Exception(String.valueOf(ki));
		}

	}

	public int getVizmennyiseg(){
		return vizmennyiseg;
	}

}
