package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Cso.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;

public class Cso extends Mezo {
	private int vizmennyiseg;

	public void Megjavit() {
		super.setMukodik(true);
	}

	public void PumpaEpit() {
	}

	public void Kilyukaszt() {
	}

	public void VizetNovel(int meret) {
		if(meret + vizmennyiseg > 1){	//MAXVIZ
			throw new BufferOverflowException();
		}
		else {
			vizmennyiseg += meret;
		}
	}

	public void VizetCsokkent(int meret) {
		if(meret < vizmennyiseg) {
			vizmennyiseg -= meret;
		}
		else{ throw new BufferUnderflowException();}

	}

	public int getVizmennyiseg(){
		return vizmennyiseg;
	}

}
