package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Cso.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Cso extends Mezo {
	private int vizmennyiseg;

	public void Megjavit() {
		super.setMukodik(true);
	}

	public void PumpaEpit() {
	}

	public void Kilyukaszt() {
	}

	public void VizetNovel(int meret) {
		vizmennyiseg += meret;
	}

	public void VizetCsokkent(int meret) {
		vizmennyiseg -= meret;
	}

	public int getVizmennyiseg(){
		return vizmennyiseg;
	}

}
