package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Forras.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Forras extends AktivElem {
	public void Frissit() {
	}
}
