package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Jatekos.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public abstract class Jatekos {
	private int maxHatizsakKapacitas;
	private Mezo helyzet;
	private List <Pumpa> pumpaHatizsak;
	private List <Cso> csoHatizsak;

	public void Lep() {
	}

	public void Allit(Mezo kimenet, Mezo bemenet) {

	}

	public Mezo getHelyzet(){
		return helyzet;
	}
}
