package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Jatekos.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.List;

public abstract class Jatekos {
	private int maxHatizsakKapacitas;
	private Mezo helyzet;
	private List<Pumpa> pumpaHatizsak;
	private List<Cso> csoHatizsak;

	public void Lep() {
	}

	/**
	 * Jatekos atallitja egy pumpa be es kimenetet
	 */
	public void Allit() {
		System.out.println("Függvényhívás: " + this + ".Allit()");
		
		List<Mezo> szomszedok = GetSzomszedok();
		
		helyzet.Atallit(szomszedok.get(0), szomszedok.get(1));
	}

	/**
	 * Jatekos helyzetének lekerdezese
	 * @return játékos helyzete
	 */
	public Mezo getHelyzet(){
		return helyzet;
	}
	
	/**
	 *  Jatekos helyzetének beállítása
	 * @param m játékos leendő helyzete
	 */
	public void setHelyzet(Mezo m) {
		helyzet = m;
	}
	
	/**
	 * Jatekos helyzetenek a szomszedainak a lekerdezese
	 * @return helyzetének a szomszédai
	 */
	public List<Mezo> GetSzomszedok(){
		System.out.println("Visszatérés: a pumpa szomszédaival");
		return helyzet.GetSzomszedok();
	}
}
