package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Mezo.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public abstract class Mezo {
	private int vizmennyiseg;
	private Boolean mukodik;
	private int maxJatekosok;

	private List <Jatekos> jatekosok;
	private ArrayList <Mezo> szomszedok;

	public Mezo(){szomszedok = new ArrayList<Mezo>();}


	public List<Mezo> GetSzomszedok() {
		return this.szomszedok;
	}

	public Boolean JatekosElfogad(Jatekos j) {
		return null;
	}

	public void JatekosEltavolit(Jatekos j) {
	}

	public void Atallit(Mezo kimenet, Mezo bemenet) {
	}

	// cso vagy pumpa megjavitasa
	public void Megjavit() {
		System.out.println("Fuggvenyhivas: Megjavit()");
		mukodik = true;
	}

	public void Kilyukaszt() {
		System.out.println("Fuggvenyhivas: Kilyukaszt()");
		mukodik = true;
	}

	public void PumpaEpit() {
	}

	public void SzomszedHozzaad(Mezo m) {
	}

	public void SzomszedTorol(Mezo m) {
	}

	public Boolean SzomszedFelcsatol(Mezo m) {
		szomszedok.add(m);
		return true;
	}

	public ArrayList<Mezo> GetLeszedhetoSzomszedok() {
		return szomszedok;
	}

	public void setMukodik(boolean status){
		mukodik = status;
	}

	public void VizetCsokkent(int meret) throws Exception {};
	public void VizetNovel(int meret) throws Exception {};
	public int getVizmennyiseg(){return vizmennyiseg;}
	
public List<Jatekos> getJatekosok() {
	return this.jatekosok;
}

public List<Pumpa> getTermeltPumpak(){
	return null;
}
public void PumpaEltavolit() {
	
}
public Cso getKimenet() {
	return null;
}
public Cso getBemenet() {
	return null;
}
}
