package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Palya.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.List;

/**
 * A Palya osztály tárolja az összes aktív elemet és a játékosokat.
 *
 */
public class Palya {
	private List<Mezo> elemek;
	private List<Jatekos> jatekosok;
}
