package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Palya.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Palya {
	private Mezo elemek;
	private Jatekos jatekosok;

}
