package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Palya.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

/**
 * A Palya osztály tárolja az összes aktív elemet és a játékosokat.
 *
 */
public class Palya {
	private List<Mezo> elemek = new ArrayList<>();
	private List<Jatekos> jatekosok = new ArrayList<>();

	public List<Mezo> getElemek() {
		return elemek;
	}

	public void setElemek(List<Mezo> elemek) {
		this.elemek = elemek;
	}

	public List<Jatekos> getJatekosok() {
		return jatekosok;
	}

	public void setJatekosok(List<Jatekos> jatekosok) {
		this.jatekosok = jatekosok;
	}
}
