package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Pumpa.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;

public class Pumpa extends AktivElem {
	private  static int MAXVIZ = 1;
	private int vizmennyiseg;
	private Cso bemenet;
	private Cso kimenet;
	private Ciszterna termeltpumpak;

	public void Atallit(Cso kimenet, Cso bemenet) {
		this.bemenet = bemenet;
		this.kimenet = kimenet;
	}

	public void Megjavit() {
	}

	public void Frissit() {

		int befolyoviz = bemenet.getVizmennyiseg();
		vizmennyiseg += befolyoviz;
		try {
			bemenet.VizetCsokkent(befolyoviz);
		}
		catch (BufferUnderflowException e){
			System.out.println("Nincs  eleg viz a csoben " + e);
		}
		int kifolyoviz = kimenet.getVizmennyiseg();	// MAXVIZ
		kifolyoviz = MAXVIZ - kifolyoviz;
		try {
			kimenet.VizetNovel(kifolyoviz);
		}
		catch (BufferOverflowException e){
			System.out.println("Nem tudsz ennyi vezet a csobe pumpalni: " + kifolyoviz + " " + e );
		}
		vizmennyiseg -= kifolyoviz;


	}
}
