package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Pumpa.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.util.ArrayList;
import java.util.List;

public class Pumpa extends AktivElem {
	private  static int MAXVIZ = 1;
	private int maxCso = 5;
	private int vizmennyiseg;
	private Mezo bemenet;
	private Mezo kimenet;
	
	/**
	 * Egy mező szomszédaihoz hozzáad egy új mezőt
	 * @param m a hozzáadandó mező
	 */
	@Override
	public void SzomszedHozzaad(Mezo m) {
		ArrayList<Mezo> szomszedok = super.GetSzomszedok();
		if(szomszedok.size() < maxCso)
			szomszedok.add(m);
		System.out.println("Függvényhívás: " + this + ".SzomszedHozzaad("+m+")");
	}

	/**
	 * Egy játékos átállítja egy pumpa be és kimenetét
	 * @param kimenet amire át lesz állítva a kimenet
	 * @param bemenet amire át lesz állítva a bemenet
	 */
	@Override
	public void Atallit(Mezo kimenet, Mezo bemenet) {
		this.bemenet = bemenet;
		this.kimenet = kimenet;
		System.out.println("Függvényhívás:  " + this + ".Atallit("+kimenet+", "+bemenet+")");
		System.out.println("Bemenet állítása: "+ this.bemenet +":Mezo\n"
				+ "Kimenet állítása: "+ this.kimenet +":Mezo");
	}

	/**
	 * A szerelő megjavít egy elemet, amin éppen áll
	 */
	@Override
	public void Megjavit() {
		System.out.println("Függvényhívás: " + this + ".Megjavit()");
		setMukodik(true);
	}

	public void Frissit() {
		System.out.println("Függvényhívás: " + this +": Frissit() ");
		int befolyoviz = MAXVIZ;
		vizmennyiseg += befolyoviz;
		try {
			bemenet.VizetCsokkent(befolyoviz);
		}
		catch (Exception e){
			vizmennyiseg -= befolyoviz-Integer.parseInt(e.getMessage());
		}


		int kifolyoviz = kimenet.getVizmennyiseg();
		kifolyoviz = MAXVIZ;

		if (kifolyoviz < vizmennyiseg) {

			try {
				kimenet.VizetNovel(kifolyoviz);
			} catch (Exception e) {
				kifolyoviz = kifolyoviz - Integer.parseInt(e.getMessage());
			}
			vizmennyiseg -= kifolyoviz;

		}
	}
}
