package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Pumpa.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;

public class Pumpa extends AktivElem {
	private  static int MAXVIZ = 1;
	private int vizmennyiseg;
	private Cso bemenet;
	private Cso kimenet;
	

	@Override
	public void Atallit(Cso kimenet, Cso bemenet) {
		this.bemenet = bemenet;
		this.kimenet = kimenet;
		System.out.println("Fuggvenyhivas: Atallit(cs1, cs2)");
		System.out.println("Bemenet allitasa: cs1:Cso\n"
				+ "Kimenet allitasa: cs2:Cso");
	}

	public void Megjavit() {
		setMukodik(true);
	}

	public void Frissit() {
		System.out.println("Függvényhívás: " + this +": Frissit() ");
		int befolyoviz = MAXVIZ;
		vizmennyiseg += befolyoviz;
		try {
			bemenet.VizetCsokkent(befolyoviz);
		}
		catch (Exception e){
			vizmennyiseg -= befolyoviz-Integer.parseInt(e.getMessage());
		}


		int kifolyoviz = kimenet.getVizmennyiseg();
		kifolyoviz = MAXVIZ;

		if (kifolyoviz < vizmennyiseg) {

			try {
				kimenet.VizetNovel(kifolyoviz);
			} catch (Exception e) {
				kifolyoviz = kifolyoviz - Integer.parseInt(e.getMessage());
			}
			vizmennyiseg -= kifolyoviz;

		}
	}
}
