package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Szabotor.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Szabotor extends Jatekos {
	public void Lyukaszt() {
		Mezo helyzet = super.getHelyzet();
		helyzet.Kilyukaszt();
	}
}
