package projlab;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : projlab.Szerelo.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Szerelo extends Jatekos {
	
	/**
	 * A szerelő megjavít egy csövet, amin éppen áll
	 */
	public void Javit() {
		System.out.println("Függvényhívás: " + this + ".Javit()");
		Mezo helyzet = super.getHelyzet();
		helyzet.Megjavit();
	}

	public void PumpatFelvesz() {
	}

	public void CsovetLecsatol() {
	}

	public void CsovetFelcsatol() {
	}

	public void PumpatEpit() {
	}
}
