/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 */

plugins {
    application
    java
}

java {
    toolchain {
        //languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("projlab.Main")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

version = "1.2.1"