//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AktivElem.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public abstract class AktivElem extends Mezo {
	private int maxCso;

	public abstract void Frissit();
}
