//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ciszterna.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Ciszterna extends AktivElem {
	private Pumpa termeltpumpak;

	public void PumpaEltavolit() {
	}

	public void PumpatKeszit() {
	}

	public void CsovetKeszit() {
	}

	public void Frissit() {
	}
}
