//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cso.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Cso extends Mezo {
	private int vizmennyiseg;

	public void Megjavit() {
	}

	public void PumpaEpit() {
	}

	public void Kilyukaszt() {
	}

	public void VizetNovel(int meret) {
	}

	public void VizetCsokkent(int meret) {
	}
}
