//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jatekos.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public abstract class Jatekos {
	private int maxHatizsakKapacitas;
	private Mezo helyzet;
	private Pumpa pumpaHatizsak;
	private Cso csoHatizsak;

	public void Lep() {
	}

	public void Allit(Mezo kimenet, Mezo bemenet) {
	}
}
