//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mezo.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public abstract class Mezo {
	private bool mukodik;
	private int maxJatekosok;
	private Jatekos jatekosok;
	private Mezo szomszedok;

	public List<Mezo> GetSzomszedok() {
	}

	public bool JatekosElfogad(Jatekos j) {
	}

	public void JatekosEltavolit(Jatekos j) {
	}

	public void Atallit(Mezo kimenet, Mezo bemenet) {
	}

	public void Megjavit() {
	}

	public void Kilyukaszt() {
	}

	public void PumpaEpit() {
	}

	public void SzomszedHozzaad(Mezo m) {
	}

	public void SzomszedTorol(Mezo m) {
	}

	public bool SzomszedFelcsatol(Mezo m) {
	}

	public List<Mezo> GetLeszedhetoSzomszedok() {
	}
}
