//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szabotor.java
//  @ Date : 2023. 03. 29.
//  @ Author : 
//
//

public class Szabotor extends Jatekos {
	public void Lyukaszt() {
	}
}
